version: '3'
services:
  # Start pulsar
  pulsar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pulsar
    hostname: pulsar
    restart: on-failure
    environment:
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
  # start consumer
  consumer:
    build: consumer
    container_name: consumer
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - PULSAR_ADDRESS=pulsar://localhost:6650
    depends_on:
      pulsar:
        condition: service_started
    command: "/bin/server"
  # start producer
  producer:
    build: producer
    container_name: producer
    ports:
      - "3001:3001"
    depends_on:
      - consumer
    environment:
      - PULSAR_ADDRESS=pulsar://localhost:6650
      - RUST_LOG=info
      - FILE_PATH=pride_mini.txt
    command: "/bin/server"
volumes:
  pulsardata:
  pulsarconf:
