[package]
name = "consumer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulsar = "6.1"
env_logger = "0.9"
log = "0.4.6"
tokio = { version = "1.0", features = ["full"]}
futures = "0.3"
